### PR TITLE
Secondary Role:  Fixed a bug where positive safety margin did not work

### LINKED ISSUE #1486: Secondary roles with positive safety margin
@firngrod would you take a look at this? 

Is the test wrong or is it a bug?

The scenario is:
- set `safetyMargin 50`
- press dual role key
- press action key
- release action key
- wait 20 ms
- release dual role key
- expect primary
- observe secondary

```
// Secondary role test: positive safetyMargin (release-order based)
// Release as secondary role, but resolve as primary due to positive safety margin.
// Key u has primary=u, secondary=LS
// Press u, press i, release i, 20ms, release u -> u i
static const test_action_t test_secondary_role_positive_safety[] = {
    TEST_SET_CONFIG("secondaryRole.defaultStrategy advanced"),
    TEST_SET_CONFIG("secondaryRole.advanced.timeout 350"),
    TEST_SET_CONFIG("secondaryRole.advanced.timeoutAction secondary"),
    TEST_SET_CONFIG("secondaryRole.advanced.safetyMargin 50"),
    TEST_SET_CONFIG("secondaryRole.advanced.triggeringEvent release"),
    TEST_DELAY__(50),
    TEST_SET_SECONDARY_ROLE("u", HID_KEYBOARD_SC_U, SecondaryRole_LeftShift),
    TEST_DELAY__(50),
    TEST_SET_ACTION("i", "i"),
    TEST_PRESS______("u"),
    TEST_DELAY__(20),
    TEST_PRESS______("i"),
    TEST_DELAY__(60),
    TEST_RELEASE__U("i"),
    TEST_DELAY__(20),
    TEST_RELEASE__U("u"),
    TEST_DELAY__(50),
    TEST_EXPECT__________("u"),
    TEST_EXPECT__________("u i"),
    TEST_EXPECT__________("u "),
    TEST_EXPECT__________(""),

    TEST_END()
};
```

Log: 
```
[TEST] Running: SecondaryRoles/positive_safety_margin
[TEST] > SetConfig 'secondaryRole.defaultStrategy advanced'
[TEST] > SetConfig 'secondaryRole.advanced.timeout 350'
[TEST] > SetConfig 'secondaryRole.advanced.timeoutAction secondary'
[TEST] > SetConfig 'secondaryRole.advanced.safetyMargin 50'
[TEST] > SetConfig 'secondaryRole.advanced.triggeringEvent release'
UP t 10444 10444
[TEST] > Delay 50ms
[TEST] > SetSecondaryRole [u] = scancode 24, secondary 2
[TEST] > Delay 50ms
[TEST] > SetAction [i] = 'i'
[TEST] > Press [u]
DOWN u 10503 10503
[TEST] > Delay 20ms
[TEST] > Press [i]
[TEST] > Delay 60ms
[TEST] > Release [i]
[TEST] > Delay 20ms
[TEST] > Release [u]
10607 u S:203
10607 OUT LS
[TEST] <   FAIL: Expect 'u', got 'LS'
DOWN i 10526 10609
10609 OUT LS- i
UP i 10586 10610
10619 OUT LS
UP u 10607 10622
10623 OUT
[TEST] > Delay 50ms
[TEST] Finished: SecondaryRoles/positive_safety_margin - FAIL
```
Steps to run the test:

Edit: the tests are implemented for uhk80 only.

Run once for timing info:
```
statsRecordKeyTiming
```
Then to run the test:
```
zephyr uhk logs 1
zephyr uhk logPriority 1
testSuite SecondaryRoles positive_safety_margin
```
See the results in the advanced settings agent log.

Edit: I have pushed code that outputs key timing into the zephyr log just recently.

### PR DESCRIPTION
**Pull request by firngrod**
Fixes #1486

### CODE REVIEW

File: right/src/secondary_role_driver.c [hunk 1]
```diff
@@ -180,6 +180,7 @@ static secondary_role_state_t resolveCurrentKeyRoleIfDontKnowTimeout()
 
     // now we want to trigger secondary, but are we allowed?
     // handle safety margin part 2: wait for the safety margin?
+    const bool safetyWaitForRelease = safetyBlockSecondary && dualRoleRelease == NULL;
```
Comment (firngrod) [inline right/src/secondary_role_driver.c:183]: Actually, the check for no dual role key release should be redundant here. If we had one, we would have reached line 176

Comment (kareltucek) [reply right/src/secondary_role_driver.c:183]: Code robustness and readability say that it is fine and probably preferred :-).
